id: P008019
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:55:54.885168
source_metadata:
  id: bdr:W1CZ1884
  title: བརྡའི་བྱེ་བྲག་རྣམ་པར་ཕྱེ་བའི་ཚིག་ལེའུར་བྱས་པ་སྨྲ་བའི་རྒྱན
  author: ''
  volumes:
    f4ef95506958469f96ff3731777aa741:
      image_group_id: I1CZ1979
      title: Volume 1 of brda'i bye brag rnam par phye ba'i tshig le'ur byas pa smra
        ba'i rgyan
      volume_number: 1
      total_pages: 80
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
