id: P008019
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1884
  title: བརྡའི་བྱེ་བྲག་རྣམ་པར་ཕྱེ་བའི་ཚིག་ལེའུར་བྱས་པ་སྨྲ་བའི་རྒྱན
  author: ''
  volumes:
    813d341643a54ea3a311f47656f5c57c:
      image_group_id: I1CZ1979
      title: ''
      volume_number: 1
      total_pages: 80
ebook_metadata:
  title: བརྡའི་བྱེ་བྲག་རྣམ་པར་ཕྱེ་བའི་ཚིག་ལེའུར་བྱས་པ་སྨྲ་བའི་རྒྱན
  author: ''
  sku: P008019
  cover: cover.jpg
  layers:
  - pagination
